python: can't open file '/tmp/gptme-evals-1r239c9d/prime.py': [Errno 2] No such file or directory
