python: can't open file '/tmp/gptme-evals-5a4wpx7m/prime.py': [Errno 2] No such file or directory
