python: can't open file '/tmp/gptme-evals-j6q9ng5_/prime.py': [Errno 2] No such file or directory
