python: can't open file '/tmp/gptme-evals-g46ldb49/hello.py': [Errno 2] No such file or directory
