python: can't open file '/tmp/gptme-evals-0ye8hw9o/prime.py': [Errno 2] No such file or directory
