python: can't open file '/tmp/gptme-evals-qjirhpd6/prime.py': [Errno 2] No such file or directory
