python: can't open file '/tmp/gptme-evals-41t204g3/prime.py': [Errno 2] No such file or directory
