python: can't open file '/tmp/gptme-evals-0ygh0n6t/prime.py': [Errno 2] No such file or directory
