python: can't open file '/tmp/gptme-evals-3wcw0dvq/prime.py': [Errno 2] No such file or directory
