python: can't open file '/tmp/gptme-evals-a2ulqc1r/prime.py': [Errno 2] No such file or directory
